### ISSUE TITLE
What happens in our database if an Influencer falls out of the list on Hive.one's list.

### ISSUE THREAD

**Issue by MadeofTin** [TennaGraph/TennaGraph#34]
![image](https://user-images.githubusercontent.com/1226869/49206359-dbdead80-f37f-11e8-9563-113b0d98d6fb.png)

This list changes ranking all the time and people drop in and out of it.

What happens to this data when we get new data from hive.one?

**Comment by MaxSemenchuk** [comment]
List is updated each 10 mins. If out – will appear in the list, but not on the graph
