### ISSUE TITLE
If a user adds a stance of an influencer it does not tag if the stance is from an influencer.

### ISSUE THREAD

**Issue by MadeofTin** [TennaGraph/TennaGraph#37]
![image](https://user-images.githubusercontent.com/1226869/49207190-3973f980-f382-11e8-93ef-9005a509d62d.png)

I added a test stance for vitalik. It did not mark that he was an influencer automatically. The influencer list should manage itself as it will change all the time.

This also supports the idea of having a stakeholder class that is separate from the influencer class.

**Comment by MaxSemenchuk** [comment]
wrong twitter handle
